In [5]:
lst = [1, 2, 3, 4, 5]
lst2 = [2, 4, 6, 8, 10]
print(sum(lst2)/len(lst2))

6.0


In [15]:
import numpy as np
a = np.array({1:"ali", 2:"reza"})
a
b = {1: "ali", 2: "reza"}
c = list(b.items())
c

[(1, 'ali'), (2, 'reza')]

In [22]:
lst = [1, 2, 3, 4, 5]
lst2 = [2, 4, 6, 8, 10]

ar1 = np.array(lst)
ar2 = np.array(lst2)
print(ar1+ar2)
print(np.mean(ar2))

[ 3  6  9 12 15]
6.0


In [25]:
lst4 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
ar4 = np.array(lst4)
print(ar4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
n = 5
for i in range(1, n+1):
    for j in range(1, n+1):
        print(i*j, end="\t")
    print()

1	2	3	4	5	
2	4	6	8	10	
3	6	9	12	15	
4	8	12	16	20	
5	10	15	20	25	


In [30]:
lst5 = [i for i in range(10, 51, 3)]
lst5

[10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]

In [31]:
ar5 = np.arange(10, 51, 3)
ar5

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [44]:
lst_6 = [1 for i in range(100)]
print(lst_6)
ar6 = np.array(lst_6)
print(ar6.reshape(10, 10))

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [ ]:
# ar6 = np.zeros(100)
# ar6

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
print(np.arange(100, 1000, 18).reshape(10, 5))

[[100 118 136 154 172]
 [190 208 226 244 262]
 [280 298 316 334 352]
 [370 388 406 424 442]
 [460 478 496 514 532]
 [550 568 586 604 622]
 [640 658 676 694 712]
 [730 748 766 784 802]
 [820 838 856 874 892]
 [910 928 946 964 982]]
